europeana/europeana-portal-collections

- .hound.yml
- .rubocop.yml
- Gemfile
- Gemfile.lock
The [Hound service](https://houndci.com/) has been given access to write to pull requests on this repo. Merging this commit just creates Hound and Rubocop configuration files to ensure that future pull requests comply with our Ruby coding style. Other language checks are disabled in .hound.yml until we agree on coding styles for them.
> Re #188: Add Hound config for Ruby

- spec/features/object_spec.rb
This feature spec always fails because: clicking on the next and previous links on object pages with Capybara does not for some reason trigger the POST action to the data-context-href attribute (/record/abc/123/track) of the <a> elements, even though it does trigger it from the search results page.
Those expectations have here been commented out.
@andyjmaclean if you are able to fix this feature spec to get it working, please do. Otherwise, please just merge as-is, as we may in future rework the next/previous link implementation to not be dependent on JS.
> Re #188: Disable previous / next link checks in object feature spec

- Gemfile
- Gemfile.lock
- app/views/templates/search/search_object.rb
*Use ajax to load (non-initial) similar items.  The first four items are loaded normally for no-js.
*Fixed another flatten.join error in search_object
> Re: #228 similar items ajax

- app/controllers/portal_controller.rb
This removes the restriction of similar items to those similar by the who field, on the object display page.
> Re #228: Retrieve similar items for all fields on object display.

- .travis.yml
- Gemfile
Ruby 2.2.1 is not supported in the CloudFoundry buildpacks used to build this application on Anynines.
It is therefore necessary to upgrade to Ruby 2.2.2.
> Re #300: Update Ruby to version 2.2.2

- app/controllers/channels_controller.rb
- app/controllers/concerns/europeana/channels.rb
- app/models/channel.rb
- config/application.rb
- spec/controllers/channels_controller_spec.rb
- spec/helpers/channels_helper_spec.rb
- spec/models/channel_spec.rb
Conversion to symbols of URL parameters is unsafe.
> Do not convert to symbols incoming URL parameters

- .travis.yml
- app/controllers/concerns/europeana/catalog.rb
- app/controllers/portal_controller.rb
- app/views/templates/search/search_object.rb
- deploy/travis/.env
- spec/controllers/channels_controller_spec.rb
- spec/controllers/home_controller_spec.rb
- spec/controllers/portal_controller_spec.rb
- spec/spec_helper.rb
- spec/support/europeana_api_helper.rb
This works by:
1. Sending an HTTP HEAD request to the media proxy service
2. Caching the response in Redis, indefinitely
This will require additional HTTP request(s) of unpredictable duration, which will have to be made by the Ruby app before any response is sent to the client (the first time each object is requested). This is not ideal. *But*, this is only an interim strategy until we have such technical metadata available via the API, later in the year.
On the object pages, the MIME type is set in the variable `@mime_type`
> Re #316: Make MIME types available to front end before rendering

- Gemfile
- Gemfile.lock
- spec/capybara_helper.rb
- spec/features/search_spec.rb
These feature specs ensure that:
1. Empty searches are permitted
2. Placeholder text is not submitted when an empty search is performed
> Re #308: Feature specs for search box behaviour.

- config/application.rb
- config/routes.rb
In production, set RELATIVE_URL_ROOT to /portal
> Re #337: Read relative URL root from ENV

- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/assets/stylesheets/blacklight.css.scss
To improve deployment times on PaaS.
> Re #348: Remove redundant refs in asset manifests

- config/application.rb
- deploy/development/config/redis.yml
As configuring by hash does not work on our PaaS.
> Re #344: Use URI for Redis cache store config

- app/views/portal/show.rb
Proxy service responds with required Access-Control-Expose-Headers header for Content-Type exposition.
> Re #343: Enable FLAC player

- Gemfile
Not possible to build Ruby 2.2.3 on A9s. Reverting Ruby to 2.2.2.
> Revert to Ruby 2.2.2

- app/views/portal/show.rb
* Re-factored the monolithic `Portal::Show#media_items` method for improved readability
* Obtain mime type of media resources from CRF metadata, not from proxy service
* Use proxy service to download hasView resources, unless they are images
* Use stock media type thumbnails for hasView resources
> Multiple media items

- app/presenters/document/record_presenter.rb
- app/views/portal/show.rb
This aims to improve readibility of the `Portal::Show` view class by breaking down its 100+ line `#data_section` method into a number of shorter methods.
> Portal show view refactor

- Gemfile
- Gemfile.lock
- app/controllers/browse_controller.rb
- app/controllers/channels_controller.rb
- app/controllers/home_controller.rb
- app/controllers/portal_controller.rb
- app/views/portal/show.rb
- spec/features/object_spec.rb
* action caching instead of fragment caching because the latter is not achievable with the Mustache template implementation
* required removal of next/previous and back to search links from object page as these vary per-request
> Re #623: action caching

- Gemfile
- Gemfile.lock
Including:
* Rails to version 4.2.5
* Nokogiri for security vulnerabilities
> Re #774, #776: update gem dependencies

- Gemfile
CI services are used to run these tools instead.
> Remove unused gems

- Gemfile
- app/controllers/application_controller.rb
- app/controllers/browse_controller.rb
- app/controllers/home_controller.rb
- app/jobs/cache/colour_facets_job.rb
- app/models/browse_entry.rb
- app/models/collection.rb
- app/models/hero_image.rb
- app/models/link.rb
- app/models/link/promotion.rb
- app/models/media_object.rb
- app/models/page.rb
- app/views/application_view.rb
- app/views/browse/colours.html.mustache
- app/views/browse/colours.rb
- app/views/browse/new_content.html.mustache
- app/views/browse/new_content.rb
- app/views/browse/sources.html.mustache
- app/views/browse/sources.rb
- app/views/collections/show.html.mustache
- app/views/collections/show.rb
- app/views/home/index.html.mustache
- app/views/home/index.rb
- app/views/portal/static.html.mustache
- app/views/portal/static.rb
- config/initializers/assets.rb
- config/initializers/cache_version.rb
- lib/clock.rb
- spec/controllers/browse_controller_spec.rb
Uses lambdas to permit Russian-doll style fragment caching with cache keys based on object timestamps.
> Re #628: fragment caching in Mustache templates

- config/initializers/rack_rewrite.rb
`Rack::Utils.parse_query` treats them as such unless the delimiter
is passed explicitly.
> Re #851: semi-colons are not URL param delimiters

- app/controllers/concerns/catalog.rb
When users have cookies disabled, POST requests will always fail, in order to prevent CSRF attacks. This is not a risk in the portal catalog scope where no data is written and no sensitive user data transmitted.
> Re #203: Skip verify_authenticity_token in Catalog

- app/helpers/mustache_helper.rb
- app/models/banner.rb
- app/models/page.rb
- app/views/application_view.rb
- app/views/collections/show.rb
- app/views/home/index.rb
- app/views/pages/show.rb
- config/initializers/rails_admin.rb
- db/migrate/20160119090126_add_banner_id_to_pages.rb
- db/migrate/20160119093141_add_default_to_banners.rb
- db/migrate/20160119093503_remove_key_from_banners.rb
- db/schema.rb
- db/seeds/banners.rb
- spec/fixtures/banner/translations.yml
- spec/fixtures/banners.yml
- spec/fixtures/links.yml
- spec/models/ability_spec.rb
- spec/models/banner_spec.rb
- spec/models/page_spec.rb
* associate `Page` with `Banner` model
* add `default` boolean attribute to `Banner`
* remove `key` string attribute from `Banner`
* max one `Banner` can have `default == true`
* default banner is shown on all pages without an explicit banner associated
> Re #869: page specific banners

- app/controllers/concerns/oembed_retriever.rb
- app/presenters/document/web_resource_presenter.rb
* Just silently catches errors from OEmbed, not attempting to render embed HTML
> Re #861: OEmbed error handling

- app/jobs/delete_old_searches_job.rb
To prevent OOM crashes on DJ workers.
> Re #928: Optimize DeleteOldSearchesJob

- app/controllers/concerns/oembed_retriever.rb
- config/initializers/oembed.rb
For CCMA, Ina.fr and Picturepipe media players.
See https://github.com/europeana/europeana-oembed-provider
> Use Europeana oEmbed provider

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/rails_admin/custom/theming.scss
- app/controllers/settings_controller.rb
- app/helpers/i18n_helper.rb
- app/views/layouts/rails_admin/_language_select.html.erb
- app/views/layouts/rails_admin/_secondary_navigation.html.haml
- app/views/settings/language.rb
- config/initializers/rails_admin.rb
- spec/config/initializers/rails_admin_spec.rb
In order to improve performance of CMS where there are many translatable content elements, and many languages, resulting in huge forms.
> Translate content in CMS via language select

- app/views/portal/show.rb
By enclosing the search terms in quotes, not parentheses
> Fix country canned search

- app/views/portal/show.rb
To avoid Ruby's time parser, e.g., interpretting "-0322" (322 BC) as something else.
> Only format dates with "-" after the first char

- app/controllers/concerns/controller_exception_handling.rb
- app/jobs/application_job.rb
Reverts europeana/europeana-portal-collections#512
We should retain the _option_ to send error report emails. In specific environments it can just be disabled by not setting the `ERROR_REPORT_MAIL_TO` env var.
> Revert "Do not send error report emails"

- app/jobs/cache/record_counts_job.rb
- app/models/collection.rb
- app/models/concerns/has_publication_states.rb
- spec/jobs/cache/record_counts_job_spec.rb
- spec/models/collection_spec.rb
* Job enqueued to retrieve the record count stats
* Job touches collection landing page on completion, to expire its cached HTML and display stats immediately
> Generate stats when a collection is published

- app/models/collection.rb
- app/views/portal/index.rb
- config/initializers/rails_admin.rb
- config/locales/rails.en.yml
- db/migrate/20160907132925_add_settings_to_collection.rb
- db/schema.rb
- spec/fixtures/collections.yml
- spec/fixtures/pages.yml
- spec/models/collection_spec.rb
- spec/support/shared_contexts/blacklight_config.rb
- spec/views/portal/index_spec.rb
Requires a `db:migrate` to add settings attribute to Collection model.
> Per-collection default search layout setting

- app/helpers/feed_helper.rb
Otherwise the return value is the enumerable passed to the block.
> Return nil if no feed image shown

- app/helpers/collections_helper.rb
- app/helpers/feed_helper.rb
- app/jobs/cache/feed/blog_job.rb
- app/models/feed_entry_image.rb
- app/views/concerns/newsworthy_view.rb
With support for extracting images from <video poster="..."/> attributes, e.g. for Tumblr.
> Add `FeedEntryImage` model

- app/presenters/concerns/document/record/iiif.rb
* Heidelberg supplies service metadata in EDM
* Bodleian manifests no longer work
> Remove Heidelberg and Bodleian IIIF hacks

- app/presenters/facet/range_presenter.rb
- spec/presenters/facet/range_presenter_spec.rb
- spec/support/shared_contexts/facet_presenter.rb
By always creating instances of `DisplayableRangeItem` even when no aggregation is needed.
Also broke down some methods to be more atomic.
> Get the facet link URLs working

- Gemfile
- Gemfile.lock
As it may break with logstash (i.e. europeana-logging) giving
`Encoding::UndefinedConversionError` exceptions.
> Move redis-rails-instrumentation to development env

- Gemfile
- Gemfile.lock
- app/views/collections/show.rb
Because landing page HTML is cached and the facet entry needs to be
random, so the JS should pick one from all after each page load.
> Cache-proof sneak peak

- Gemfile
- Gemfile.lock
- app/controllers/galleries_controller.rb
- app/models/collection.rb
- app/models/gallery.rb
- app/views/concerns/gallery_displaying_view.rb
- app/views/galleries/index.rb
- app/views/galleries/show.rb
- config/initializers/rails_admin.rb
- config/routes.rb
- db/migrate/20170131150633_add_slug_to_gallery.rb
- db/migrate/20170131154042_associate_gallery_with_collection.rb
- db/schema.rb
- spec/controllers/galleries_controller_spec.rb
- spec/fixtures/galleries.yml
- spec/models/collection_spec.rb
- spec/models/gallery_spec.rb
- spec/routing/galleries_routing_spec.rb
* Associate galleries with collections to support "themed" galleries
* Galleries have unique titles enforced not by validation but by the `Gallery` model automatically appending a number to the end of the title until it is unique
* Galleries have slugs used in their URLs, auto-generated by the stringex gem
* Gallery index and show page URLs are beneath /explore
> Gallery refinements

- app/controllers/portal_controller.rb
- app/views/portal/show.rb
- config/initializers/rails_admin.rb
- spec/controllers/portal_controller_spec.rb
- spec/fixtures/api_response/record_with_edm_dataprovider.json.erb
- spec/fixtures/data_providers.yml
- spec/support/helpers/europeana_api_helper.rb
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/1841
You will need to enter the CMS and upload a logo for one of the pre-populated Fashion data providers, e.g. Pucci Archive. When you then view the item page for an item from that data provider, e.g. /2048205/SC0215701, then a variable `@data_provider` is available to the view, and the view method `#data_provider_logo_url` can be used to get the URL of the logo image.
> Load data provider on item page

- app/controllers/galleries_controller.rb
- app/views/galleries/index.rb
- spec/controllers/galleries_controller_spec.rb
A default of 24 galleries are shown per page. This can be overriden via the `per_page` URL param, which will facilitate testing.
> Gallery foyer pagination

- app/models/ability.rb
- app/models/categorisation.rb
- app/models/collection.rb
- app/models/concerns/is_categorisable.rb
- app/models/gallery.rb
- app/models/topic.rb
- config/initializers/rails_admin.rb
- config/locales/rails.en.yml
- db/migrate/20170207155507_create_topics.rb
- db/migrate/20170208102105_create_categorisations.rb
- db/schema.rb
- db/seeds/topics.rb
- db/seeds/topics.yml
- spec/config/initializers/rails_admin_spec.rb
- spec/models/ability_spec.rb
- spec/models/categorisation_spec.rb
- spec/models/collection_spec.rb
- spec/models/gallery_spec.rb
- spec/models/topic_spec.rb
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/1905
Using this requires running both `db:migrate` and `db:seed` (latter is non-destructive)
Galleries can be assigned a topic from a pre-seeded list in the CMS.
Topics are associated with galleries, via a polymorphic association on the other new model, Categorisation. The reason for this approach instead of adding a foreign key to the galleries table is that it makes it trivial in future to make other models categorisable using these topics, without adding foreign keys to their tables.
One thing that is not great yet is the way the topic input is presented in the RailsAdmin CMS for a gallery, where it appears as a nested form beneath categorisation. Any ideas on how to improve that, simplifying it to just have the topic …
> Topics & Categorisations

- app/controllers/portal_controller.rb
Because similar items are never displayed if a hierarchy is present.
> Make hierarchies API request before similar items

- app/models/categorisation.rb
- spec/models/categorisation_spec.rb
Else validation on categorisable objects fails if they are new records.
> Remove categorisable presence validation

- app/views/collections/show.rb
- config/initializers/rails_admin.rb
- config/locales/rails.en.yml
- db/migrate/20170220131250_add_newsletter_url_to_page.rb
- db/schema.rb
- db/seeds/collections.rb
- db/seeds/landing_pages.rb
- spec/fixtures/pages.yml
- spec/models/page/landing_spec.rb
This adds a newsletter_url column to the pages table and uses it instead of the one from the collections table.
Removal of the collections table's column should happen separately, and after these changes have been released.
> add newsletter_url to landing pages

- .env.example
- app/controllers/application_controller.rb
By setting env var `DELETE_X_FRAME_OPTIONS_RESPONSE_HEADER=1`
> Allow deletion of X-Frame-Options response header

- app/models/gallery.rb
- spec/models/gallery_spec.rb
Increase the galley image count limit to 48 in accordance with https://europeanadev.assembla.com/spaces/europeana-npc/tickets/1987-up-the-amount-of-maximum-images-in-the-gallery/details#
> update the gallery image limit to 48

- app/controllers/galleries_controller.rb
- app/views/galleries/show.html.mustache
- app/views/galleries/show.rb
- spec/controllers/galleries_controller_spec.rb
- spec/fixtures/api_response/search.json.erb
- spec/fixtures/gallery_images.yml
- spec/models/gallery_spec.rb
This adds the hero_image_url for gallery show pages to the cache so it's also available when we don't make an API request because we have cached the page body.
I guess there is a small chance that the image url which is written to the cache expires a few milliseconds before the page's cached body expires, in which case it potentially could lead to the og metadata being left blank for a request during that time. However the likelihood of this is very remote and the consequences not really significant.
> cache hero_image_url for galleries head meta

- app/models/collection.rb
- app/models/page/landing.rb
- config/initializers/rails_admin.rb
- db/migrate/20170307114233_add_collection_to_pages.rb
- db/schema.rb
- spec/fixtures/collections.yml
- spec/fixtures/pages.yml
- spec/jobs/cache/record_counts_job_spec.rb
- spec/models/collection_spec.rb
- spec/models/page/landing_spec.rb
These changes link collections and landing pages. This refactor is mainly in preparation for adding more authorization logic, so it also makes various adjustments to the CMS, most of which restrict the ability to change collection keys, or associations between collections and landing pages. This is in order to only allow these values to be set on creation of new collections/landingpages(which only administrators will be able to do)
> Re: #1978 connect collections and landing pages

- app/views/collections/show.rb
If I create a landing page with no body then publish it and try to view, the app errors because the view does not check for a nil body. This change fixes that.
> Check if landing page body is nil before using

- .env.example
- Gemfile
- Gemfile.lock
- app/controllers/blog_posts_controller.rb
- app/controllers/concerns/homepage_hero_image.rb
- app/controllers/galleries_controller.rb
- app/models/page/landing.rb
- app/models/pro.rb
- app/models/pro/base.rb
- app/models/pro/blog_post.rb
- app/models/pro/network.rb
- app/views/blog_posts/index.html.mustache
- app/views/blog_posts/index.rb
- app/views/concerns/paginated_view.rb
- app/views/galleries/index.rb
- app/views/portal/index.rb
- config/initializers/env.rb
- spec/controllers/blog_posts_controller_spec.rb
- spec/fixtures/api_response/pro_blog_posts.json.erb
- spec/models/page/landing_spec.rb
- spec/models/pro/base_spec.rb
- spec/models/pro/network_spec.rb
- spec/models/pro_spec.rb
- spec/views/blog_posts/index_spec.rb
- spec/views/concerns/paginated_view_examples.rb
- spec/views/concerns/paginated_view_spec.rb
- spec/views/galleries/index_spec.rb
- spec/views/portal/index_spec.rb
* Extracts view logic for pagination into a PaginatedView concern, also used by main item search results and galleries listing
* Changes the Pro URL env var to be the base URL for the entire site, not that for the JSON API
* Implements most display elements for blog listing page, only missing read time (to come later)
> Blog listing display

- app/models/ability.rb
- app/models/feed.rb
- app/models/user.rb
- config/initializers/rails_admin.rb
- spec/fixtures/permissions.yml
- spec/models/ability_spec.rb
- spec/models/feed_spec.rb
- spec/models/user_spec.rb
This is to remove the permissions of Editors on Feeds, only Administrators should be able to create these.
> remove feed permissions-from-editors

- config/initializers/rails_admin.rb
- lib/rails_admin/config/fields/extensions/generic_help.rb
- spec/config/initializers/rails_admin_spec.rb
For max length from ActiveModel validations.
Max length hint on string fields comes from: https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config/fields/types/string.rb#L22-L39
No equivalent on text fields: https://github.com/sferik/rails_admin/blob/master/lib/rails_admin/config/fields/types/text.rb
This PR duplicates the code for the `#generic_help` method on the former and injects it into the latter.
Style violations in the duplicated method will not be fixed here.
> Add #generic_help to RailsAdmin text fields

- Gemfile
- Gemfile.lock
- app/controllers/blog_posts_controller.rb
- app/controllers/concerns/paginated_controller.rb
- app/controllers/events_controller.rb
- app/controllers/galleries_controller.rb
- app/models/pro/base.rb
- app/models/pro/blog_post.rb
- app/models/pro/event.rb
- app/views/blog_posts/index.rb
- app/views/concerns/paginated_json_api_result_set_view.rb
- app/views/events/index.html.mustache
- app/views/events/index.rb
- app/views/events/show.html.mustache
- app/views/events/show.rb
- config/routes.rb
- spec/controllers/blog_posts_controller_spec.rb
- spec/controllers/concerns/paginated_controller_spec.rb
- spec/controllers/events_controller_spec.rb
- spec/controllers/galleries_controller_spec.rb
- spec/models/pro/base_spec.rb
- spec/models/pro/event_spec.rb
- spec/routing/events_routing_spec.rb
- spec/views/blog_posts/index_spec.rb
Initial implementation of events retrieval from Pro site's JSON API.
* Views show some basic data as a POC; full population pending template implementation
* Pagination of JSON API result sets extracted into a new view concern
* Pagination in controllers extracted into a controller concern, but not applied to `PortalController` as that has multiple actions paginating different result sets, plus Blacklight handles pagination for `#index`
> Events from Pro via JSON API

- Gemfile
- Gemfile.lock
Re CVE-2016-4658
But unlocked in the Gemfile for easier future updating.
> Update Nokogiri to 1.7.1

- app/helpers/record_helper.rb
- app/views/concerns/gallery_displaying_view.rb
- spec/fixtures/api_response/search.json.erb
Because the thumbnail API does not perform well enough for many thumbnails on one page.
> Get gallery thumbnails straight from S3

- .env.example
- Gemfile
- Gemfile.lock
- app/controllers/blog_posts_controller.rb
- app/controllers/concerns/pro_json_api_consumer.rb
- app/controllers/events_controller.rb
- app/presenters/pro_resource_presenter.rb
- app/views/blog_posts/index.rb
- app/views/concerns/theme_filterable_view.rb
- app/views/events/index.rb
- app/views/events/show.rb
- config/initializers/env.rb
- spec/controllers/blog_posts_controller_spec.rb
- spec/controllers/events_controller_spec.rb
- spec/fixtures/api_response/pro_blog_posts.json.erb
- spec/presenters/pro_resource_presenter_spec.rb
- spec/views/blog_posts/index_spec.rb
* Events and blog posts from Pro JSON API are now always filtered by tag: "culturelover" for all, "culturelover-fashion" for Fashion
* Labels on tiles on listing pages are taken from any "culturelover-theme" tags, with a lookup for a label in the `Topic` model, where "theme" from the tag needs to match a topic slug
* Events can be filtered by theme, but this is not exposed unless `ENABLE_EVENTS_THEME_FILTER` is set
* Events default to future events only, but can be switched to show past, although the front-end does not respect the field name defined for this
> Filtering blog posts and events

- .env.example
- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/galleries_controller.rb
- app/views/application_view.rb
- app/views/blog_posts/show.html.mustache
- app/views/blog_posts/show.rb
- app/views/collections/show.html.mustache
- app/views/concerns/cacheable_view.rb
- app/views/events/show.html.mustache
- app/views/events/show.rb
- app/views/explore/colours.html.mustache
- app/views/explore/new_content.html.mustache
- app/views/explore/people.html.mustache
- app/views/explore/periods.html.mustache
- app/views/explore/sources.html.mustache
- app/views/explore/topics.html.mustache
- app/views/galleries/index.html.mustache
- app/views/galleries/show.html.mustache
- app/views/galleries/show.rb
- app/views/home/index.html.mustache
- app/views/pages/show.html.mustache
- config/initializers/env.rb
- config/routes.rb
- spec/controllers/galleries_controller_spec.rb
Re https://app.assembla.com/spaces/europeana-npc/tickets/1997-omit-csrf-meta-tags-from-html-head/details
CSRF tokens can instead be requested in advance of affected AJAX requests by sending a pre-flight GET request to /portal/csrf.json
Blog posts, events and galleries now have their full HTML cached, avoiding the need for various workarounds to repopulate elements in the HTML head when the body was cached and API calls not made to supply the data.
> No CSRF meta tags

- app/views/collections/show.rb
The changes made are using FacetLinkGroupPresenter instead of calling the FacetPresenter directly since the FacetPresenter needs a Europeana::Blacklight::Response::Facets::FacetItem and the Europeana::Blacklight::Response::Facets::FacetField the FacetLinkGroupPresenter works with the FacetEntry directly so it keeps the facet_entry_display_value method cleaner.
> use FacetLinkGroupPresenter for preview search label

- Gemfile
- Gemfile.lock
- app/models/hero_image.rb
- app/views/concerns/hero_image_displaying_view.rb
- config/edm/rights.yml
- config/initializers/rails_admin.rb
- spec/models/hero_image_spec.rb
Re: https://app.assembla.com/spaces/europeana-npc/tickets/2184, and refactoring https://github.com/europeana/europeana-portal-collections/pull/901
* Gemfile updates the styleguide to a hotfixed version of it for a localisation update: https://github.com/europeana/europeana-styleguide-ruby/commit/bd0bffedbb8e09ce4f9bb2d3fa9365f20b3a0af6 (renaming Public Domain license i18n key from "pdm" to "public")
* URLs to link to from hero images are added to the config/edm/rights.yml
* All rights in that YAML file having a url like that are considered eligible for hero image licenses, and hero image license enum is populated on that basis
* In the CMS, rights labels are now displayed instead of keys
> Hero licenses from edm rights

- app/models/hero_image.rb
- app/views/concerns/hero_image_displaying_view.rb
- spec/models/hero_image_spec.rb
The main problem here was that we never had the URLs anywhere and weren't setting license_url for the template.
This PR updates the licenses we use to conform with the list as per https://europeanadev.assembla.com/spaces/europeana-npc/tickets/2184
> re: #2184 hero license links added to concern

- app/models/page/landing.rb
- app/views/collections/show.rb
- app/views/galleries/index.rb
- app/views/home/index.rb
- spec/fixtures/links.yml
- spec/fixtures/media_objects.yml
- spec/fixtures/pages.yml
- spec/models/page/landing_spec.rb
- spec/views/collections/show_spec.rb
For browse landing pages use the image from the promo tile at position 0, if this isn't found for any reason or the landing page is using the default display, default to the hero image.
+specs
> use zero promo tile for og:image on browse landing pages

- app/presenters/document/field_group_presenter.rb
entity_label returns a string which needs to be converted into an array in order for any? to work correctly.
> Convert entity_label return value to an array

- app/controllers/entities_controller.rb
- app/views/concerns/entity_displaying_view.rb
- app/views/entities/show.rb
- spec/views/entities/show_spec.rb
Please review.
Note that thumbnail is either `src` or `full` however `full` might not exist meaning a blank image while `src` works and might be much larger.
> Entity page meta tags

- .env.example
- Gemfile.lock
- app/helpers/i18n_helper.rb
- app/presenters/concerns/facet/labelling.rb
- app/views/application_view.rb
- app/views/concerns/navigable_view.rb
- config/initializers/env.rb
- config/initializers/i18n_available_locales.rb
- spec/config/initializers/i18n_available_locales_spec.rb
- spec/presenters/facet/simple_presenter_spec.rb
- spec/support/shared_examples/common_view_components.rb
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/2338
* Additional locales can be specified in the env var `I18N_ADDITIONAL_LOCALES` (see .env.example)
* Language name lookups are moved to the I18n scope `global.languages`
> Configurable additional locales

- Gemfile
- Gemfile.lock
uses the #2399 hotfix branch from europeana-i18n-ruby:
https://github.com/europeana/europeana-i18n-ruby/commits/hotfix/2399-gaeilge
> Re: #2399 latest translations

- Gemfile
- Gemfile.lock
This uses the a branch from the [europeana-i8n gem](https://github.com/europeana/europeana-i18n-ruby) to only cherry-pick new Irish translations into the previously released version.
> re: #2404 new irish translations

- app/helpers/api_helper.rb
- app/helpers/media_proxy_helper.rb
- spec/helpers/media_proxy_helper_spec.rb
add the api_url parameter to media_proxy requests in order to identify requests to proxy media not yet in production
> add api_url to media_proxy params

- app/presenters/document/web_resource_presenter.rb
So that Mustache skips it instead of rendering "false"
> nil instead of false if no download URL

- app/presenters/concerns/blacklight_document_presenter.rb
- app/presenters/document/record_presenter.rb
- app/presenters/document/search_result_presenter.rb
- app/views/portal/show.rb
To prevent double HTML escaping in combination with Blacklight.
Re: https://europeana.atlassian.net/browse/EC-2524
> Fetch dataProvider direct from document

- Gemfile
- Gemfile.lock
- config/initializers/session_store.rb
- db/migrate/20171121121759_add_sessions_table.rb
- db/schema.rb
- lib/clock.rb
- spec/config/initializers/session_store_spec.rb
Re: https://europeana.atlassian.net/browse/EC-2520
Because some model validation flash messages get too long for cookie storage.
> Switch to ActiveRecord for session storage

- Gemfile.lock
- app/presenters/concerns/blacklight_document_presenter.rb
> use "; " as a separator for field values

- app/models/user.rb
To prevent FK constraint exceptions when deleting users who published galleries.
> Nullify gallery published_by when user is deleted

- app/models/gallery_image/europeana_record_api.rb
`Rack::Utils.parse_query` already unescapes them in this context.
> Prevent double-unescaping of gallery image URLs

- app/presenters/facet/boolean_presenter.rb
- app/presenters/facet/collection_presenter.rb
- app/presenters/facet/hierarchical_presenter.rb
- app/presenters/facet_presenter.rb
- spec/support/shared_contexts/facet_presenter.rb
- spec/support/shared_examples/facet_presenter.rb
Using `String` because using `Blacklight::SearchState` and `Hash` is too expensive for large numbers of facet values.
> Optimise facet URL generation

- Gemfile.lock
- app/models/europeana/record/set.rb
- app/models/page_element.rb
- config/initializers/rails_admin.rb
- spec/models/europeana/record/set_spec.rb
The tabbed association objects in RailsAdmin are already sortable with jQuery UI Sortable, and we already have [custom JS](https://github.com/europeana/europeana-portal-collections/blob/develop/app/assets/javascripts/rails_admin/custom/ui.js) to apply the  sorting to a `position` field if present on the nested form.
This works by delegating position from the record set to the joining page element. The caveat is that it does not work for new record sets, which will always be added to the end of the list when the page is saved, but may subsequently be ordered.
> Make record sets positionable

- db/migrate/20180427125141_add_image_portal_urls_to_gallery.rb
- db/migrate/20180430075313_add_image_errors_to_gallery.rb
- db/migrate/20180625102705_create_europeana_record_sets.rb
To prevent migration failure from schema version 20180430075313 to 20180730121538 on this branch.
> Declare model class in migration

- Gemfile.lock
- app/controllers/collections_controller.rb
- app/controllers/concerns/blacklight_config.rb
- app/controllers/concerns/catalog.rb
- app/presenters/concerns/facet/item_display.rb
- app/presenters/concerns/facet/labelling.rb
- app/presenters/concerns/facet/url.rb
- app/presenters/facet/collection_presenter.rb
- app/presenters/facet_presenter.rb
- app/views/concerns/searchable_view.rb
- spec/controllers/collections_controller_spec.rb
- spec/features/collection_search_spec.rb
- spec/features/newspapers_collection_spec.rb
- spec/presenters/facet/collection_presenter_spec.rb
- spec/support/shared_contexts/collection_with_custom_api_url.rb
To introduce a pseudo-facet for the Newspapers collection to switch between its custom API and the default, this:
* abstracts some of the collection-facet-specific presentation logic to be reusable across single-selection (i.e. radio button) facets, and pseudo-facets not in fact sent to the API
* breaks the `FacetPresenter` class's methods down into more modules
* adds an "api" facet to the "newspapers" collection
* skips the use of a per-collection API in the collection search if this facet has the value "default" selected (as in default API, not default radio button)
* outputs URL paths instead of full URLs for facet links, to reduce page weight
> Pseudo-facet API toggle for newspapers collection
