- .hound.yml
- .rubocop.yml
- Gemfile
- Gemfile.lock
Alternative merge for master so that Hound picks up our config.
> Re #188: Add Hound config for Ruby

- Gemfile
- Gemfile.lock
- app/controllers/concerns/europeana/catalog.rb
- app/controllers/portal_controller.rb
- app/helpers/mustache_helper.rb
- spec/controllers/portal_controller_spec.rb
- spec/features/search_spec.rb
- spec/helpers/url_helper_spec.rb
- spec/support/europeana_api_helper.rb
- spec/views/templates/search/search_home_spec.rb
- spec/webmock_helper.rb
Some specs were out of date. This merge fixes them along with some other tweaks to fix issues the specs exposed.
> Get specs running again.

- app/helpers/mustache_helper.rb
- app/views/templates/search/search_object.rb
Removed "public" from js_path defined in mustache_helper
Added nil checking on dctermsCreated
> Re:267 fixed js path and nil exception on dctermsCreated

- Gemfile
- Gemfile.lock
- app/helpers/mustache_helper.rb
- app/views/templates/search/channels_landing.rb
- app/views/templates/search/search_object.rb
- config/locales/en.yml
- config/locales/global/en.yml
- config/locales/global/nl.yml
- config/locales/nl.yml
Following the merge the PDF viewer will be testable at this url:
http://localhost:3000/record/09336/72B195E7174360280218AE261368B22242AC4E09.htmStill to do:
I'm mapping type:text to type:pdf to get the pdf player to work.
This will need changed to what the technical metadata / heder service returns.
Downloads needs to be a sub-model of items.
> Re: #247 - player integration

- app/views/templates/search/search_object.rb
* changed flac to audio in media_type method
* added logic to use the edm_is_shown_by_download_url for flac files; aurora uses an ajax call to pull in flac files
> re: #249 - videojs - prototype

- Gemfile
- Gemfile.lock
- config/environments/production.rb
To improve deployment times on PaaS.
> Remove redundant gems.

- Gemfile
- Gemfile.lock
- config/locales/global/en.yml
- config/locales/global/nl.yml
This replaces the pull request "Re: #406 - translations for global menu" which was a branch based on the wrong parent branch.
> Re: #406 - translations for global menu clean branch

- app/views/portal/index.rb
- config/channels/music.yml
I had to make a change to:
app/views/portal/index.rb
because this url was crashing:
http://localhost:3000/portal/channels/music?q=paris
(it crashed before I made the query change too - see here: http://acceptance.npc.eanadev.org/portal/channels/music?q=paris)
> Re: #427 updated music query

- app/helpers/mustache_helper.rb
- app/models/page.rb
- app/views/portal/static.rb
- db/seeds.rb
- spec/fixtures/pages.yml
- spec/models/page_spec.rb
* Adds help and contact pages
* Adds template support for navigation between pages
> Re #653: static pages w/ nav

- app/views/application_view.rb
- app/views/browse/colours.rb
- app/views/browse/new_content.rb
- app/views/browse/sources.rb
- app/views/collections/show.rb
- app/views/home/index.rb
- app/views/portal/static.rb
- spec/views/browse/new_content_spec.rb
"Europeana Collections" set as site title in `ApplicationView`
> Re #772: Update page title for "Europeana Collections"

- app/models/banner.rb
To invalidate their cached versions as all display it.
> Re #628: Make phase feedback banner touch published pages

- app/views/portal/show.rb
> Re #786: All fielded searches from records are queries

- app/models/link/promotion.rb
- spec/models/link/promotion_spec.rb
Added app, timeline, playlist and gallery.
> Re #876: Add more promotion types

- Gemfile
- Gemfile.lock
> Bump styleguide ref

- app/helpers/collections_helper.rb
- app/helpers/mustache_helper.rb
To reduce duplication of published collections logic.
> Re #868: Revise collection_filter_options helper

- app/jobs/delete_old_searches_job.rb
Because it crashes our DJ workers.
> Re #928: Hotfix to optimize delete old searches

- app/helpers/time_date_helper.rb
- app/views/portal/show.rb
- config/application.rb
- config/initializers/time_formats.rb
And set the site timezone to Amsterdam.
> Re #369: helper to convert Unix timestamps to local time

- Gemfile
- Gemfile.lock
- app/controllers/concerns/blacklight_config.rb
- app/presenters/facet/range_presenter.rb
- app/views/portal/index.rb
Enable with env var `FACET_YEAR_FIELD`
> Re #932: enable year facet

- lib/tasks/jobs.rake
Tasks:
* `jobs:cache:colour_facets`
* `jobs:cache:record_counts`
* `jobs:cache:recent_additions`
* `jobs:cache:providers`
> Rake tasks to trigger cache-refreshing jobs

- config/initializers/delayed_job.rb
> Re #951: Raise exception on SIGTERM

- app/presenters/document/record_presenter.rb
- app/presenters/document/web_resource_presenter.rb
Unless they are in edm:hasView. (On the record page.)
> Hide edm:object thumbnails

- app/helpers/mustache_helper.rb
- app/jobs/cache/feed_job.rb
- lib/tasks/jobs.rake
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/1074
> Language-specific exhibitions RSS

- app/views/portal/show.rb
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/1177
> Agents contextual display

- app/controllers/concerns/catalog.rb
- app/helpers/mustache_helper.rb
- app/helpers/url_helper.rb
- spec/features/search_spec.rb
And make empty search spec actually test something.
> Move empty search handling to UrlHelper

- Gemfile
- Gemfile.lock
- app/controllers/collections_controller.rb
- app/models/page.rb
- app/views/collections/show.rb
- config/initializers/rails_admin.rb
- config/locales/rails_admin.en.yml
- db/migrate/20160606101323_add_strapline_to_pages.rb
- db/migrate/20160606103934_populate_home_landing_page_strapline.rb
- db/schema.rb
> Collection landing page straplines

- app/controllers/concerns/blacklight_config.rb
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/1218
> Increase max per page to 96

- app/presenters/document_presenter.rb
Re: https://www.assembla.com/spaces/europeana-npc/tickets/1274
> Hotfix for specific licenses

- app/jobs/cache/feed_job.rb
- lib/clock.rb
- lib/tasks/jobs.rake
Also replace `SCHEDULE_BLOG_*` env vars with one `SCHEDULE_FEED_BLOGS` env var
> Add fashion blog

- app/controllers/concerns/controller_exception_handling.rb
- app/jobs/application_job.rb
> Do not send error report emails

- Gemfile
- Gemfile.lock
For updated browse translations
> Bump styleguide gem ref

- app/views/portal/index.rb
So that it works within collections
> Use search_action_path in viewoptions

- .travis.yml
From: https://github.com/travis-ci/travis-ci/issues/3225#issuecomment-200965782
> Try to get phantomjs working on Travis

- app/controllers/concerns/controller_exception_handling.rb
Reverts europeana/europeana-portal-collections#513
See #538
> Revert "Remove old method call"

- app/controllers/concerns/blacklight_config.rb
- app/presenters/concerns/facet/labelling.rb
From cc_skos_prefLabel.en to proxy_dc_type.en, only those values starting with "Object Type: "
> Change fashion item type facet source

- app/jobs/application_job.rb
- app/jobs/cache/colour_facets_job.rb
From background job that retrieves facet counts per-collection for the browse by colours page.
> Remove colourpalette limit

- .ruby-style.yml
- config/rubocop/default.yml
- config/rubocop/disabled.yml
- config/rubocop/enabled.yml
Because Hound CI does not support inherit_from with remote URLs. :(
> Copy Rubocop defaults into config/

- app/controllers/collections_controller.rb
- app/controllers/home_controller.rb
- app/helpers/record_counts_helper.rb
- app/jobs/cache/record_counts_job.rb
- app/views/concerns/browsable_view.rb
- spec/views/collections/show_spec.rb
Use added to restriction of browse menu links
> Record count cache helper methods

- app/controllers/portal_controller.rb
- spec/controllers/portal_controller_spec.rb
- spec/fixtures/api_response/no_hierarchy.json.erb
- spec/fixtures/api_response/record.json.erb
- spec/fixtures/api_response/record_with_dcterms_haspart.json.erb
- spec/fixtures/api_response/record_with_dcterms_ispartof.json.erb
- spec/fixtures/api_response/search.json.erb
- spec/fixtures/api_response/search_facet_data_provider.json.erb
- spec/fixtures/api_response/search_facet_provider.json.erb
- spec/support/helpers/europeana_api_helper.rb
- spec/support/shared_examples/europeana_api_requests.rb
i.e. those with either dcterms:hasPart or dcterms:isPartOf present.
> Only retrieve hierarchy for some records

- app/controllers/browse_controller.rb
- app/controllers/concerns/enforce_default_format.rb
- app/controllers/pages_controller.rb
- app/views/concerns/navigable_view.rb
- spec/controllers/browse_controller_spec.rb
- spec/controllers/pages_controller_spec.rb
- spec/features/locale_session_spec.rb
- spec/requests/default_extension_spec.rb
- spec/support/shared_examples/common_view_components.rb
- spec/support/shared_examples/page_with_top_nav.rb
- spec/views/application_view_spec.rb
- spec/views/browse/colours_spec.rb
- spec/views/browse/new_content_spec.rb
- spec/views/browse/people_spec.rb
- spec/views/browse/sources_spec.rb
- spec/views/browse/topics_spec.rb
- spec/views/collections/show_spec.rb
- spec/views/home/index_spec.rb
- spec/views/pages/custom/errors/not_found_spec.rb
- spec/views/pages/show_spec.rb
- spec/views/portal/index_spec.rb
- spec/views/portal/show_spec.rb
Should have .html at the end of them. Also those pages should have alternate link elements.
> Static & browse page urls

- app/views/portal/show.rb
Until deprecated MapQuest service replaced
> Hide maps on record pages

- deploy/pivotal/config/paperclip.yml
> Set Fog host from `AWS_HOST`

- app/controllers/concerns/blacklight_config.rb
* Get up to 10,000 values from API
* Display negative single year values
> Adjust retrieval of date facet

- Gemfile
- Gemfile.lock
- app/presenters/concerns/facet/labelling.rb
For proxy_dcterms_created facet label
> Update styleguide gem

- app/jobs/cache/colour_facets_job.rb
- app/jobs/cache/record_counts/data_providers_job.rb
- app/jobs/cache/record_counts/providers_job.rb
- app/jobs/concerns/api_querying_job.rb
And a refactor to DRY up those similar jobs.
> Explicit limits on job facet fields

- app/helpers/api_helper.rb
- app/helpers/record_helper.rb
- app/presenters/document/web_resource_presenter.rb
- app/views/portal/index.rb
Or fallback to default API URL.
> Get thumbnails from API URL in query params

- app/helpers/collections_helper.rb
- app/views/application_view.rb
- app/views/collections/show.rb
- app/views/portal/index.rb
- spec/fixtures/collection/translations.yml
- spec/fixtures/collections.yml
- spec/fixtures/page/translations.yml
- spec/fixtures/pages.yml
- spec/support/shared_examples/view_version.rb
- spec/views/collections/show_spec.rb
- spec/views/explore/colours_spec.rb
- spec/views/explore/new_content_spec.rb
- spec/views/explore/people_spec.rb
- spec/views/explore/sources_spec.rb
- spec/views/explore/topics_spec.rb
- spec/views/home/index_spec.rb
- spec/views/pages/show_spec.rb
- spec/views/portal/index_spec.rb
- spec/views/portal/show_spec.rb
Landing page and search results
> Beta flag only on fashion collection

- Gemfile
- Gemfile.lock
For the templates to fix the leaking brand circles.
> Update the styleguide

- app/presenters/facet_presenter.rb
> Extract active facet filters from URL params

- app/controllers/collections_controller.rb
- app/controllers/portal_controller.rb
- app/presenters/document/search_result_presenter.rb
- app/views/portal/index.rb
- app/views/portal/show.rb
Added bonus of always getting a thumbnail in search results even when
edmPreview is empty.
> Fix the similar items thumbnail URLs

- app/models/link.rb
- app/models/link/social_media.rb
- app/views/collections/show.rb
- spec/models/link/social_media_spec.rb
- spec/models/link_spec.rb
Re https://europeanadev.assembla.com/spaces/europeana-npc/tickets/1790
> Better social media link detection + Linkedin

- app/views/concerns/searchable_view.rb
i.e. ENABLE_SEARCH_FORM_AUTOCOMPLETE=1
> Make autocomplete enabled by env var

- app/controllers/concerns/europeana/annotations_api_consumer.rb
Re https://app.assembla.com/spaces/europeana-npc/tickets/1853
> Also display isShownAt and isShownBy annotations

- app/controllers/concerns/europeana/annotations_api_consumer.rb
- spec/controllers/concerns/europeana/annotations_api_consumer_spec.rb
- spec/fixtures/api_response/annotations_fetch.json.erb
- spec/fixtures/api_response/annotations_search.json.erb
- spec/support/helpers/europeana_api_helper.rb
Because the Annotations API is about to change its default from minimal to standard.
> Handle both minimal and standard profile annotations

- app/models/gallery.rb
- config/locales/rails_admin.en.yml
- spec/models/gallery_spec.rb
> Validate 6-24 images on a gallery

- app/controllers/galleries_controller.rb
- app/models/europeana/record.rb
- app/models/gallery.rb
- spec/controllers/galleries_controller_spec.rb
- spec/models/gallery_spec.rb
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/1906
> Gallery image validations from EDM

- app/presenters/concerns/document/record/iiif.rb
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/1879
> Add support for single IIIF images

- app/controllers/galleries_controller.rb
- spec/controllers/galleries_controller_spec.rb
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/1940
When there are no galleries to display, do not search the API...
> No galleries, no API

- app/controllers/galleries_controller.rb
- app/models/gallery.rb
- app/models/topic.rb
- app/views/galleries/index.rb
- spec/controllers/galleries_controller_spec.rb
- spec/fixtures/categorisations.yml
- spec/fixtures/topic/translations.yml
- spec/fixtures/topics.yml
allows filtering of galleries via topics
note: the url parameter is theme as that is what it was called previously
> Filtering of galleries

- Gemfile
- Gemfile.lock
- app/helpers/i18n_helper.rb
And update translations via styleguide
> Enable Estonian UI language

- Gemfile
- Gemfile.lock
To include session ID in payload
> Bump europeana-logging gem version

- app/models/edm/rights.rb
But with extra checking for blank values
> Fallback to default locale in EDM::Rights#label

- db/migrate/20170220154035_drop_collections_galleries_table.rb
- db/schema.rb
remove the now obsolete collections_galleries table
> remove galleries_collections table

- config/edm/rights.yml
- spec/models/edm/rights_spec.rb
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/1977
> Handle https:// in rights URLs

- app/controllers/concerns/controller_exception_handling.rb
- spec/controllers/portal_controller_spec.rb
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/1822
> Respond with 404 when record not found

- app/presenters/document/search_result_presenter.rb
- app/views/galleries/show.rb
Here needed for gallery image metadata display.
> Rights data for search result presenters

- app/controllers/galleries_controller.rb
So that appending .json does not render the source code...
> Add respond_to to galleries controller actions

- Gemfile.lock
- app/controllers/concerns/europeana/annotations_api_consumer.rb
> Handle plain text API responses in annotations

- app/presenters/blog_post_presenter.rb
- spec/presenters/blog_post_presenter_spec.rb
Else JsonApiClient fails re https://github.com/chingor13/json_api_client/issues/218
Sample blog post affected by this when hooked up to pro-beta.europeana.eu: http://localhost:3000/portal/en/blogs/meet-the-members-council-joke-van-der-leeuw-roord
> Handle missing related content

- .env.example
- app/views/application_view.rb
- config/initializers/env.rb
- config/initializers/europeana.rb
* Store in `Rails.application.config.x.google[:analytics_key]`
* Add view method `#config` returning `Rails.application.config`
* Move some other env vars into `Rails.application.config.x`
> Read Google Analytics key from env var

- app/controllers/concerns/blacklight_config.rb
- app/models/edm/rights.rb
- app/presenters/concerns/facet/labelling.rb
- config/edm/rights.yml
- lib/clock.rb
- spec/models/edm/rights_spec.rb
Two bug fixes:
* Fix rights statements not showing on item pages when rights URIs start https://
* Fix scheduled feed updating jobs not getting queued
> Hotfix v1.8.1

- app/controllers/portal_controller.rb
- app/views/portal/show.rb
- spec/controllers/portal_controller_spec.rb
With the option retained to request them now by URL param `similar=now`
> By default, request similar items later

- .env.example
- app/controllers/blog_posts_controller.rb
- app/controllers/concerns/controller_exception_handling.rb
- app/models/pro/base.rb
- app/presenters/blog_post_presenter.rb
- app/views/blog_posts/index.rb
- app/views/blog_posts/show.rb
- app/views/concerns/paginated_json_api_result_set_view.rb
- app/views/concerns/paginated_view.rb
- app/views/concerns/searchable_view.rb
- config/initializers/env.rb
- spec/controllers/blog_posts_controller_spec.rb
- spec/presenters/blog_post_presenter_spec.rb
- spec/views/blog_posts/index_spec.rb
* Hard-coded fashion option for the equivalent tag on Pro. This and any other options will likely need to remain hard-coded as this app has no way of deducing dynamically which tags from Pro should be in the list of options.
* Also included are a couple of bug fixes for pagination
> Filter blogs by theme

- Gemfile
- Gemfile.lock
- app/controllers/blog_posts_controller.rb
- app/presenters/pro_resource_presenter.rb
- app/views/blog_posts/index.rb
1. Current theme detection on the blog posts theme filter was not working
2. Stop linking to author pages on Pro, with accompanying styleguide gem update
> Blog post tweaks

- app/controllers/blog_posts_controller.rb
- app/controllers/events_controller.rb
- app/presenters/pro_resource_presenter.rb
- app/views/events/show.rb
- spec/controllers/blog_posts_controller_spec.rb
- spec/controllers/events_controller_spec.rb
* 404 if requested event is not found on Pro
* Add geolocation to event view data, for display as map
* Filters, commented out, pending available data on Pro for testing
> Event tweaks

- app/controllers/events_controller.rb
- app/helpers/cache_helper.rb
- app/views/application_view.rb
- app/views/blog_posts/show.rb
- app/views/concerns/cacheable_view.rb
- app/views/events/show.html.mustache
- app/views/events/show.rb
Also introduce a reusable `ApplicationView#page_title` method to save repeating it in every view class.
> Cache events from Pro JSON API

- config/routes.rb
simple redirect logic added to routes.rb 
Assembla ticket: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/1995
> redirects for old help pages

- app/controllers/concerns/europeana/annotations_api_consumer.rb
- spec/fixtures/api_response/annotations_search.json.erb
- spec/support/helpers/europeana_api_helper.rb
Assembla ticket: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/2111
> Handle both target_id and target_uri with Annotations API

- config/initializers/rack_middleware.rb
- lib/rack/enforce_http_host.rb
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/2148
> Rack middleware to enforce HTTP host

- config/edm/rights.yml
> update license urls

- app/controllers/collections_controller.rb
- app/models/collection.rb
- app/views/concerns/ugc_content_displaying_view.rb
- config/routes.rb
- spec/models/collection_spec.rb
- spec/routing/collections_routing_spec.rb
Not "firstworldwar".
Refactored to hard-code "world-war-I" only once.
Re https://app.assembla.com/spaces/europeana-npc/tickets/2213
> UGC content on collection "world-war-I"

- app/controllers/concerns/pro_json_api_consumer.rb
- app/presenters/pro_resource_presenter.rb
- db/migrate/20170613101708_rename_first_world_war_topic.rb
- db/schema.rb
- db/seeds/topics.yml
- spec/controllers/concerns/pro_json_api_consumer_spec.rb
- spec/fixtures/topic/translations.yml
- spec/fixtures/topics.yml
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/2032
* Expose all topics from the CMS in the blog posts drop-down
* db migration to rename "First World War" topic to "World War I"
> Blog filter topics

- app/controllers/concerns/pro_json_api_consumer.rb
- db/seeds/topics.rb
- db/seeds/topics.yml
Re: https://app.assembla.com/spaces/europeana-npc/tickets/2032-import-europeana-end-user-blog-posts-to-pro/details
Requires `rake db:seed` (non-destructive)
> Add missing topics

- Gemfile
- Gemfile.lock
- app/controllers/concerns/blacklight_config.rb
- app/presenters/concerns/facet/labelling.rb
- app/views/portal/index.rb
Re: https://app.assembla.com/spaces/europeana-npc/tickets/2240
> Add UGC facet to WWI collection

- app/views/portal/index.rb
To fix the per_page button on the 'all' collection
> re: #2248 use within_collection? method for per_page

- app/presenters/concerns/document/field/entities.rb
- app/presenters/document/field_group_presenter.rb
- app/views/portal/show.rb
- config/record_field_groups.yml
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/2257
* favour displaying edm:begin and edm:end for timespans instead of their URI, when available
* favour skos:prefLabel for places instead of their URI, when available
Plus some code tidy up.
> Treat timespans and place as entities in field groups

- Gemfile
- Gemfile.lock
Re https://europeanadev.assembla.com/spaces/europeana-npc/tickets/1990
> Europeana::I18n gem

- Gemfile
- Gemfile.lock
- app/helpers/cache_helper.rb
- app/jobs/cache/expiry/global_nav_job.rb
- app/jobs/cache/feed_job.rb
- app/models/nav_cache_invalidation_observer.rb
- app/views/concerns/navigable_view.rb
- config/application.rb
- config/initializers/env.rb
- spec/jobs/cache/expire/global_nav_job_spec.rb
So that we don't make dozens of DB queries on every page load
> Cache primary nav items

- .env.example
- app/views/application_view.rb
- config/initializers/env.rb
Re https://europeanadev.assembla.com/spaces/europeana-npc/tickets/2216/details?comment=1238096163
> Set Google Optimize container ID from env var

- db/seeds/landing_pages.rb
fixes the seeds for landing pages
> add collection to landing page seeds

- app/controllers/concerns/pro_json_api_consumer.rb
- spec/controllers/concerns/pro_json_api_consumer_spec.rb
Re: https://app.assembla.com/spaces/europeana-npc/tickets/2185/details?comment=1255992973
> Only show Fashion and WWI topics for Pro blogs

- app/views/concerns/entity_displaying_view.rb
Re https://app.assembla.com/spaces/europeana-npc/tickets/2285/details?comment=1256047043
> Handle arrays of values for prefLabel

- app/presenters/document/field_group_presenter.rb
- config/record_field_groups.yml
Re: https://app.assembla.com/spaces/europeana-npc/tickets/2266-limit-number-of-dcterms-haspart-relations-displayed-on-item-page/details
> Limit dcterms:hasPart values displayed

- app/controllers/concerns/pro_json_api_consumer.rb
- app/presenters/pro_resource_presenter.rb
- spec/controllers/concerns/pro_json_api_consumer_spec.rb
- spec/presenters/pro_resource_presenter_spec.rb
Re https://app.assembla.com/spaces/europeana-npc/tickets/2032/details?comment=1257439113
> Filter Pro resource by collection, not topic

- .env.example
- app/controllers/blog_posts_controller.rb
- app/controllers/concerns/pro_json_api_consumer.rb
- app/views/blog_posts/index.rb
- app/views/events/index.rb
- config/initializers/env.rb
- spec/controllers/blog_posts_controller_spec.rb
- spec/controllers/concerns/pro_json_api_consumer_spec.rb
- spec/fixtures/collections.yml
- spec/fixtures/page/translations.yml
- spec/fixtures/pages.yml
- spec/views/blog_posts/index_spec.rb
Re: https://app.assembla.com/spaces/europeana-npc/tickets/2185
> Remove feature toggle for Pro resource collection filter

- app/controllers/blog_posts_controller.rb
- app/controllers/events_controller.rb
- spec/controllers/blog_posts_controller_spec.rb
- spec/controllers/events_controller_spec.rb
Re: https://app.assembla.com/spaces/europeana-npc/tickets/2331
> Pro JSON API sorting

- app/helpers/collections_helper.rb
- app/models/collection.rb
- app/models/page/landing.rb
- app/views/concerns/collection_using_view.rb
- spec/views/portal/index_spec.rb
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/2320
> Do not show two links to home in breadcrumbs

- app/presenters/document/field_group_presenter.rb
Re: https://app.assembla.com/spaces/europeana-npc/tickets/2313
> Hotfix scalar entity labels

- app/views/application_view.rb
- app/views/blog_posts/show.rb
- app/views/collections/show.rb
- app/views/entities/show.rb
- app/views/events/show.rb
- app/views/galleries/index.rb
- app/views/galleries/show.rb
- app/views/home/index.rb
- app/views/portal/show.rb
- spec/support/shared_examples/common_view_components.rb
Re: https://app.assembla.com/spaces/europeana-npc/tickets/2305/details?comment=1259401353
> Site-wide og:site_name meta tag

- .env.example
- app/controllers/concerns/europeana/entities_api_consumer.rb
- app/controllers/entities_controller.rb
- app/helpers/entities_helper.rb
- app/presenters/document/field_group_presenter.rb
- config/initializers/env.rb
- config/routes.rb
- spec/controllers/concerns/europeana/entities_api_consumer_spec.rb
- spec/controllers/entities_controller_spec.rb
- spec/fixtures/api_response/entities_fetch.json.erb
- spec/fixtures/api_response/record_with_entity_agent.json.erb
- spec/helpers/entities_helper_spec.rb
- spec/routing/entities_routing_spec.rb
- spec/views/portal/show_spec.rb
Re: https://app.assembla.com/spaces/europeana-npc/tickets/2316
> Friendly entity page URLs

- app/views/application_view.rb
- spec/support/shared_examples/common_view_components.rb
- spec/views/blog_posts/index_spec.rb
- spec/views/blog_posts/show_spec.rb
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/2254
> Localised site name

- app/views/galleries/index.rb
re: #2333 remove the logic for adding info tooltips to galleries.
> remove galleries tooltip methods

- config/initializers/assets.rb
Re: https://app.assembla.com/spaces/europeana-npc/tickets/2341
> Add europeana-i18n gem version to assets cache version

- Gemfile.lock
- app/views/concerns/entity_displaying_view.rb
- spec/views/concerns/entity_displaying_view_spec.rb
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/2346/details?comment=1277498833
> Entity description title

- app/presenters/concerns/facet/labelling.rb
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/2388
> Re: #2388 Remove space in label '3D'

- config/initializers/oembed.rb
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/2422
> Add EUScreen oEmbed provider

- app/helpers/record_helper.rb
- app/helpers/thumbnail_helper.rb
- app/presenters/document/search_result_presenter.rb
- app/presenters/document/web_resource_presenter.rb
- app/presenters/facet_link_group_presenter.rb
- app/views/concerns/gallery_displaying_view.rb
- app/views/portal/show.rb
- spec/helpers/thumbnail_helper_spec.rb
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/2396
> API thumbnails

- app/helpers/media_proxy_helper.rb
- app/presenters/document/web_resource_presenter.rb
- app/views/concerns/gallery_displaying_view.rb
- app/views/galleries/show.rb
- spec/helpers/media_proxy_helper_spec.rb
Re: https://europeanadev.assembla.com/spaces/europeana-npc/tickets/2395
> use media-proxy for galleries if set

- app/presenters/document/record_presenter.rb
- app/presenters/document/web_resource_presenter.rb
- config/initializers/oembed.rb
Re: https://app.assembla.com/spaces/europeana-npc/tickets/2426
> EUscreen tweaks

- app/views/concerns/named_entity_displaying_view.rb
- spec/views/concerns/named_entity_displaying_view_spec.rb
re: #2439
3. Records with a strange "Entities - Place Term" link that return an error page (status 500) when clicked
> check URLS for named entities

- app/jobs/gallery_validation_job.rb
- app/mailers/gallery_validation_mailer.rb
- app/views/gallery_validation_mailer/post.text.erb
To include gallery title, be less repetitive, and introduce some whitespace.
> Reword galleries email

- .env.example
- app/jobs/cache/feed_job.rb
- app/views/concerns/navigable_view.rb
- db/seeds/feeds.rb
- lib/clock.rb
- lib/tasks/jobs.rake
Re: https://europeana.atlassian.net/browse/EC-2501
> Move Exhibitions feeds into db

- .env.example
- app/views/application_view.rb
- config/initializers/env.rb
- spec/capybara_helper.rb
- spec/support/shared_examples/common_view_components.rb
- spec/views/collections/show_spec.rb
Re: https://europeana.atlassian.net/browse/EC-2452
Env var is `GOOGLE_ANALYTICS_LINKED_DOMAINS`
> Set googleAnalyticsLinkedDomains JS var from env

- app/controllers/portal_controller.rb
- app/views/portal/show.rb
- spec/controllers/portal_controller_spec.rb
Re: https://europeana.atlassian.net/browse/EC-2359
via AJAX
> EC-2359: Never request annotations now, always later

- app/views/portal/show.rb
Re: https://europeana.atlassian.net/browse/EC-2524
> Use unescaped page content heading for title

- app/controllers/galleries_controller.rb
- app/controllers/portal_controller.rb
- app/helpers/gallery_helper.rb
- app/helpers/thumbnail_helper.rb
- app/views/concerns/gallery_displaying_view.rb
- app/views/galleries/index.rb
- app/views/portal/galleries.json.jbuilder
- app/views/portal/gallery.json.erb
- config/routes.rb
- spec/controllers/galleries_controller_spec.rb
- spec/controllers/portal_controller_spec.rb
- spec/helpers/thumbnail_helper_spec.rb
- spec/routing/portal_routing_spec.rb
Re: https://europeana.atlassian.net/browse/EC-2503
Also:
* Use thumbnail API for gallery thumbs, not S3
* Stop querying Search API on gallery foyer, use stored image URLs instead
> Add record gallery.json method

- app/presenters/document/field_group/section_presenter.rb
- spec/presenters/document/field_group_presenter_spec.rb
> Fix broken max field item enforcement

- config/record_field_groups.yml
https://europeana.atlassian.net/browse/EC-1766
> Proxy dc:date values may be timespan entity URIs

- app/presenters/facet/range_presenter.rb
- spec/presenters/facet/range_presenter_spec.rb
Re: https://europeana.atlassian.net/browse/EC-2553
> Improve performance of range facet presenter

- Gemfile
- Gemfile.lock
- config/initializers/session_store.rb
- db/migrate/20171206084927_drop_sessions.rb
- db/schema.rb
- lib/clock.rb
- spec/config/initializers/session_store_spec.rb
Re: https://europeana.atlassian.net/browse/EC-2581
> Revert to cookie session storage

- Gemfile.lock
- app/views/concerns/searchable_view.rb
Re: https://europeana.atlassian.net/browse/EC-2550
> Prefix search tags for entities with entity type label

- app/presenters/concerns/document/record/iiif.rb
Re: https://europeana.atlassian.net/browse/EC-2575
> Only manifest IIIF where item has relevant proxies.dcIdentifier

- Gemfile.lock
Re https://nvd.nist.gov/vuln/detail/CVE-2017-17042
> Update yard for CVE-2017-17042

- app/models/edm/rights.rb
> Replace parenthesised pattern segments with "*"

- config/initializers/rails_admin.rb
Re: https://github.com/sferik/rails_admin/issues/2502
> Prevent RailsAdmin querying of JSON fields

- app/views/concerns/localisable_view.rb
> Use strings in localising URL helpers

- app/models/gallery_image/http_response.rb
> Gallery displayability network error handling

- app/helpers/date_helper.rb
- app/views/portal/promo_card.json.jbuilder
- spec/views/portal/promo_card.json_spec.rb
* Strip HTML from title and description
* Truncate long description to 200 characters
* Format dates as Y-m-d
> Normalise promo card text

- app/models/ability.rb
- app/models/concerns/is_permissionable.rb
To prevent over-eager SQL collection lookups
> Use blocks to test abilities

- Gemfile
- Gemfile.lock
> Bump europeana-logging
